config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  resources :users do
    resource :game do
      resource :players
    end
  end

   root 'pages#home'
   
   get '/about' => 'pages#about'
   
   get '/join' => 'pages#join'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  has_many :players, :dependent => :destroy
end

app/models/plan.rb
class Game < ActiveRecord::Base
  
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :authenticate_user!, except: :show
    before_action :only_current_user, except: :show
    # http_basic_authenticate_with name: "axel", password: "hawker", only: :show
    before_filter :restrict, :only=>:show

    def show
        
    end
    
    def new
        # form for user to create game details
         @user = User.find( params[:user_id] )
        if @user.game
            redirect_to edit_user_game_path( params[:user_id])
        else
        @game = Game.new
        end
    end
    
    #Create a new game. If you already have a game it will overwrite it.
    def create
        @user = User.find( params[:user_id] )
        @game = @user.build_game(game_params)
        if @game.save
          flash[:success] = "Game Created!"
          redirect_to user_path( params[:user_id] )
        else
          render action: :new
        end
    end
    
    def edit
        @user = User.find( params[:user_id])
        @game = @user.game
    end
    
    def update
        @user = User.find( params[:user_id])
        @game = @user.game
        if @game.update_attributes(game_params)
            flash[:success] = "Game Updated!"
            redirect_to user_path(params[:user_id])
        else
            render action :edit
        end
        
    end
    
    def destroy
        @user = User.find( params[:user_id])
        @game = @user.game
        @game.destroy
        redirect_to user_path(params[:user_id])
    end
    
    private
    # You need to sanitize all the params you are passing from your create form
        def game_params
          params.require(:game).permit(:gamename, :entrycode)
        end
        
        def only_current_user
            @user = User.find( params[:user_id])
            redirect_to(root_url) unless @user == current_user
        end
    #For game#show, use password-only authentication
        def restrict
            @user = User.find( params[:user_id])
            @entrycode = @user.game.entrycode    
            
            unless params[:entrycode] == @entrycode
                flash[:danger] = "Enter a Game Code to Join the Game"
                redirect_to(root_url)
            end
           
        end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
    end
    
    def about
    end
    
    def join
        @gamecode = params[:gamecode]
        @game = Game.find_by_entrycode(@gamecode)
        if @game
            @user_id = @game.user_id
            redirect_to(user_game_path(@user_id, entrycode: @gamecode))
        else
            flash[:danger] = "Game Does Not Exist"
            redirect_to(root_url)
        end
    end
end

private
    # def page_params
    #       params.require(:game).permit(:gamename, :entrycode)
    # end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    
    def show
        @user=User.find( params[:id])
    end
    
    #Create a new Player. If you already have a game it will overwrite it.
    def create
        @user = User.find( params[:user_id] )
        @game = @user.game
        
        @player = @game.players.build(player_params)
        if @player.save
          flash[:success] = "Player Created!"
          redirect_to user_path( params[:user_id] )
        else
          render action: :new
        end
    end
    
    def destroy
        @user = User.find( params[:user_id])
        @game = @user.game
        @game.players.destro
    end
    
    
    
    def new
        # form for user to create game details
        @user = User.find( params[:user_id] )
        @player = Player.new
        
    end

    private
    # You need to sanitize all the params you are passing from your create form
        def player_params
          params.require(:player).permit(:player_name, :player_code, :balance)
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user=User.find( params[:id])
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/_form.html.erb
<%= form_for @game, url: user_game_path do |f| %>
  <div class="form-group">
    <%= f.label :gamename %>
    <%= f.text_field :gamename, class: 'form-control' %>
  </div>
  
  <% unless current_user.game %>
    <% @entrycode = SecureRandom.hex(3) %>
    <div class="form-group">
      <%= f.hidden_field :entrycode, :value => @entrycode  %>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.submit "Setup Game", class: 'btn btn-primary' %>
  </div>
  
<% end %>

app/views/games/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Edit Your Game</h1>
    <p class="text-center">Modify the Settings of your game</p>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Setup Your Game</h1>
    <p class="text-center">Setup your first game and start playing!</p>
    <div class="well">
      <%= form_for @game, url: user_game_path do |f| %>
        <div class="form-group">
          <%= f.label :gamename %>
          <%= f.text_field :gamename, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.submit "Setup Game", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<h2>Your Game(Game-Show)</h2>
<% @user = User.find( params[:user_id]) %>
<% if @user.game %>
    <table class = 'table'>
        <tr>
            <th>Game ID</th>
            <th>Game Name</th>
            <th>Entry Code</th>
            <th>Created On</th>
            <th>Last Updated</th>
        </tr>
        <tr>
            <td><%= @user.game.id %></td>
            <td><%= @user.game.gamename %></td>
            <td><%= @user.game.entrycode %></td>
            <td><%= @user.game.created_at %></td>
            <td><%= @user.game.updated_at %></td>
        </tr>
    </table>
    <h2>Players</h2>
    <% @players = @user.game.players %>
    <table class='table-striped table'>
        <tr>
            <th>Player Name</th>
            <th>Player Code</th>
            <th>Balance</th>
        </tr>
        <% @players.each do |p| %>
        <tr>
            <td> <%= p.player_name %></td>
            <td> <%= p.player_code %></td>
            <td> <%= p.balance %></td>
        </tr>
    <% end %>
    </table>
    <%= link_to "Add a Player", new_user_game_players_path(current_user), class: "btn btn-primary" if current_user %>
<% else %>
    <p>You currently don't have a game setup. Why Don't you start one?</p>
    <%= link_to "Create A New Game", new_user_game_path(current_user) if current_user %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Banker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
      <i class="fa fa-dollar"></i>
      Banker
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <div class="nav navbar-nav navbar-right" >  
        <% if current_user %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
        <% else %>
          <%= link_to "Login", new_user_session_path, method: :get, class: 'btn btn-primary navbar-btn' %>
          <%= link_to "Sign Up", new_user_registration_path, method: :get, class: 'btn btn-success navbar-btn' %>
        <% end %>
    </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/pages/_joinform.html.erb
<%= form_tag("/join", method: "get" ) do %>
  <div class="form-group">
    <%= label_tag(:gamecode, "Game Entry Code") %>
    <%= text_field_tag(:gamecode) %>
  </div>
  
  <div class="form-group">
    <%= submit_tag( "Join Game") %>
  </div>
  
<% end %>

app/views/pages/about.html.erb
<h2>About Banker</h2>

app/views/pages/home.html.erb
<h2>Home</h2>
<% if user_signed_in? %>
    <% if current_user.game %>
        <%= link_to "Edit Your Game", edit_user_game_path(current_user) if current_user %>
       <%= link_to "Reset Your Game", user_game_path(current_user), method: :delete, data: { confirm: 'Are you certain you want to reset your game? There is no undo for this.' } if current_user %>
    <% else %>
        <%= link_to "Create A New Game", new_user_game_path(current_user) if current_user %>
    <% end %>
<% else %>
    <p>Sign up or sign in</p>

<% end %>

<%= render 'joinform' %>

app/views/players/_form.html.erb
<%= form_for @player, url: user_game_players_path do |f| %>
  <div class="form-group">
    <%= f.label :player_name %>
    <%= f.text_field :player_name, class: 'form-control' %>
  </div>
  
  <% @playercode = SecureRandom.hex(3) %>
  <div class="form-group">
    <%= f.hidden_field :player_code, :value => @playercode  %>
  </div>
    
  <div class="form-group">
    <%= f.label :balance %>
    <%= f.number_field :balance, class: 'form-control' %>
  </div>  
  
  <div class="form-group">
    <%= f.submit "Add Player", class: 'btn btn-primary' %>
  </div>
  
<% end %>

app/views/players/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Setup Your Game</h1>
    <p class="text-center">Setup your first game and start playing!</p>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h2>Your Game</h2>
Game Name: <%= @user.game.gamename %><br />
Entry Code: <%= @user.game.entrycode %><br />
Created on: <%= @user.game.created_at %><br />
Last Updated: <%= @user.game.updated_at %><br />